/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_lidar_demo_nativeinterface_array_ArrayReturnTest */

#ifndef _Included_com_example_lidar_demo_nativeinterface_array_ArrayReturnTest
#define _Included_com_example_lidar_demo_nativeinterface_array_ArrayReturnTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_lidar_demo_nativeinterface_array_ArrayReturnTest
 * Method:    add
 * Signature: (Lcom/example/lidar_demo/nativeinterface/array/User;)I
 */
JNIEXPORT jint JNICALL Java_com_example_lidar_1demo_nativeinterface_array_ArrayReturnTest_add
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_example_lidar_demo_nativeinterface_array_ArrayReturnTest
 * Method:    makeIntArr
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_lidar_1demo_nativeinterface_array_ArrayReturnTest_makeIntArr
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_lidar_demo_nativeinterface_array_ArrayReturnTest
 * Method:    setIntArr
 * Signature: ([II)I
 */
JNIEXPORT jint JNICALL Java_com_example_lidar_1demo_nativeinterface_array_ArrayReturnTest_setIntArr
  (JNIEnv *, jclass, jintArray, jint);

/*
 * Class:     com_example_lidar_demo_nativeinterface_array_ArrayReturnTest
 * Method:    readyToGetStruct
 * Signature: ([J[J[J[JI)V
 */
JNIEXPORT void JNICALL Java_com_example_lidar_1demo_nativeinterface_array_ArrayReturnTest_readyToGetStruct
  (JNIEnv *, jclass, jlongArray, jlongArray, jlongArray, jlongArray, jint);

/*
 * Class:     com_example_lidar_demo_nativeinterface_array_ArrayReturnTest
 * Method:    getStruct
 * Signature: ([J[J[J[J)V
 */
JNIEXPORT void JNICALL Java_com_example_lidar_1demo_nativeinterface_array_ArrayReturnTest_getStruct
  (JNIEnv *, jclass, jlongArray, jlongArray, jlongArray, jlongArray);

/*
 * Class:     com_example_lidar_demo_nativeinterface_array_ArrayReturnTest
 * Method:    testStruct
 * Signature: (I)[Lcom/example/lidar_demo/nativeinterface/array/TestStruct;
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_lidar_1demo_nativeinterface_array_ArrayReturnTest_testStruct
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_lidar_demo_nativeinterface_array_ArrayReturnTest
 * Method:    readyToGetIntArray
 * Signature: ([I[II)V
 */
JNIEXPORT void JNICALL Java_com_example_lidar_1demo_nativeinterface_array_ArrayReturnTest_readyToGetIntArray
  (JNIEnv *, jclass, jintArray, jintArray, jint);

/*
 * Class:     com_example_lidar_demo_nativeinterface_array_ArrayReturnTest
 * Method:    readyToGetFloatArray
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_lidar_1demo_nativeinterface_array_ArrayReturnTest_readyToGetFloatArray
  (JNIEnv *, jclass);

/*
 * Class:     com_example_lidar_demo_nativeinterface_array_ArrayReturnTest
 * Method:    getFloatArray
 * Signature: ([F[F)V
 */
JNIEXPORT void JNICALL Java_com_example_lidar_1demo_nativeinterface_array_ArrayReturnTest_getFloatArray
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
