/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_gsmdemo_nativeinterface_uart_UartSpring */

#ifndef _Included_com_example_gsmdemo_nativeinterface_uart_UartSpring
#define _Included_com_example_gsmdemo_nativeinterface_uart_UartSpring
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_gsmdemo_nativeinterface_uart_UartSpring
 * Method:    phone_call
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_gsmdemo_nativeinterface_uart_UartSpring_phone_1call
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_gsmdemo_nativeinterface_uart_UartSpring
 * Method:    phone_msg_send
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_gsmdemo_nativeinterface_uart_UartSpring_phone_1msg_1send
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_example_gsmdemo_nativeinterface_uart_UartSpring
 * Method:    phone_call_fin
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_gsmdemo_nativeinterface_uart_UartSpring_phone_1call_1fin
  (JNIEnv *, jclass);

/*
 * Class:     com_example_gsmdemo_nativeinterface_uart_UartSpring
 * Method:    phone_msg_send_fin
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_gsmdemo_nativeinterface_uart_UartSpring_phone_1msg_1send_1fin
  (JNIEnv *, jclass);

/*
 * Class:     com_example_gsmdemo_nativeinterface_uart_UartSpring
 * Method:    gsm_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_gsmdemo_nativeinterface_uart_UartSpring_gsm_1init
  (JNIEnv *, jclass);

/*
 * Class:     com_example_gsmdemo_nativeinterface_uart_UartSpring
 * Method:    print
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_gsmdemo_nativeinterface_uart_UartSpring_print
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
